export const drawerWidth = 240;

export const SHARED_ACTIONS = {
  MENU_TOGGLE: 'MENU_TOGGLE',
  DRAWER_TOGGLE: 'DRAWER_TOGGLE',
  SEARCH: 'SEARCH',
  SEARCH_REJECTED: 'SEARCH_REJECTED',
  START_SEARCH: 'START_SEARCH',
  CHANGE_THEME: 'CHANGE_THEME'
};

export const AUTH_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_ORG: 'SET_ORG',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_REJECTED: 'LOGIN_REJECTED'
};

export const PROJECT_ACTIONS = {
  SET_PROJECT: 'SET_PROJECT'
};
